// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcservice.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "rpcservice.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protorpc {

namespace {

const ::google::protobuf::Descriptor* ListRpcRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ListRpcRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* ListRpcResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ListRpcResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetServiceRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetServiceRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetServiceResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetServiceResponse_reflection_ = NULL;
const ::google::protobuf::ServiceDescriptor* RpcService_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_rpcservice_2eproto() {
  protobuf_AddDesc_rpcservice_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "rpcservice.proto");
  GOOGLE_CHECK(file != NULL);
  ListRpcRequest_descriptor_ = file->message_type(0);
  static const int ListRpcRequest_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ListRpcRequest, service_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ListRpcRequest, list_method_),
  };
  ListRpcRequest_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ListRpcRequest_descriptor_,
      ListRpcRequest::default_instance_,
      ListRpcRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ListRpcRequest, _has_bits_[0]),
      -1,
      -1,
      sizeof(ListRpcRequest),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ListRpcRequest, _internal_metadata_),
      -1);
  ListRpcResponse_descriptor_ = file->message_type(1);
  static const int ListRpcResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ListRpcResponse, error_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ListRpcResponse, service_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ListRpcResponse, method_name_),
  };
  ListRpcResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ListRpcResponse_descriptor_,
      ListRpcResponse::default_instance_,
      ListRpcResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ListRpcResponse, _has_bits_[0]),
      -1,
      -1,
      sizeof(ListRpcResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ListRpcResponse, _internal_metadata_),
      -1);
  GetServiceRequest_descriptor_ = file->message_type(2);
  static const int GetServiceRequest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetServiceRequest, service_name_),
  };
  GetServiceRequest_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetServiceRequest_descriptor_,
      GetServiceRequest::default_instance_,
      GetServiceRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetServiceRequest, _has_bits_[0]),
      -1,
      -1,
      sizeof(GetServiceRequest),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetServiceRequest, _internal_metadata_),
      -1);
  GetServiceResponse_descriptor_ = file->message_type(3);
  static const int GetServiceResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetServiceResponse, error_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetServiceResponse, proto_file_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetServiceResponse, proto_file_name_),
  };
  GetServiceResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetServiceResponse_descriptor_,
      GetServiceResponse::default_instance_,
      GetServiceResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetServiceResponse, _has_bits_[0]),
      -1,
      -1,
      sizeof(GetServiceResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetServiceResponse, _internal_metadata_),
      -1);
  RpcService_descriptor_ = file->service(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_rpcservice_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ListRpcRequest_descriptor_, &ListRpcRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ListRpcResponse_descriptor_, &ListRpcResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetServiceRequest_descriptor_, &GetServiceRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetServiceResponse_descriptor_, &GetServiceResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_rpcservice_2eproto() {
  delete ListRpcRequest::default_instance_;
  delete ListRpcRequest_reflection_;
  delete ListRpcResponse::default_instance_;
  delete ListRpcResponse_reflection_;
  delete GetServiceRequest::default_instance_;
  delete GetServiceRequest_reflection_;
  delete GetServiceResponse::default_instance_;
  delete GetServiceResponse_reflection_;
}

void protobuf_AddDesc_rpcservice_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protorpc::protobuf_AddDesc_rpc_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020rpcservice.proto\022\010protorpc\032\trpc.proto\""
    ";\n\016ListRpcRequest\022\024\n\014service_name\030\001 \001(\t\022"
    "\023\n\013list_method\030\002 \001(\010\"`\n\017ListRpcResponse\022"
    "\"\n\005error\030\001 \002(\0162\023.protorpc.ErrorCode\022\024\n\014s"
    "ervice_name\030\002 \003(\t\022\023\n\013method_name\030\003 \003(\t\")"
    "\n\021GetServiceRequest\022\024\n\014service_name\030\001 \002("
    "\t\"e\n\022GetServiceResponse\022\"\n\005error\030\001 \002(\0162\023"
    ".protorpc.ErrorCode\022\022\n\nproto_file\030\002 \003(\t\022"
    "\027\n\017proto_file_name\030\003 \003(\t2\225\001\n\nRpcService\022"
    ">\n\007listRpc\022\030.protorpc.ListRpcRequest\032\031.p"
    "rotorpc.ListRpcResponse\022G\n\ngetService\022\033."
    "protorpc.GetServiceRequest\032\034.protorpc.Ge"
    "tServiceResponseB\003\200\001\001", 501);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "rpcservice.proto", &protobuf_RegisterTypes);
  ListRpcRequest::default_instance_ = new ListRpcRequest();
  ListRpcResponse::default_instance_ = new ListRpcResponse();
  GetServiceRequest::default_instance_ = new GetServiceRequest();
  GetServiceResponse::default_instance_ = new GetServiceResponse();
  ListRpcRequest::default_instance_->InitAsDefaultInstance();
  ListRpcResponse::default_instance_->InitAsDefaultInstance();
  GetServiceRequest::default_instance_->InitAsDefaultInstance();
  GetServiceResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_rpcservice_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_rpcservice_2eproto {
  StaticDescriptorInitializer_rpcservice_2eproto() {
    protobuf_AddDesc_rpcservice_2eproto();
  }
} static_descriptor_initializer_rpcservice_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int ListRpcRequest::kServiceNameFieldNumber;
const int ListRpcRequest::kListMethodFieldNumber;
#endif  // !_MSC_VER

ListRpcRequest::ListRpcRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protorpc.ListRpcRequest)
}

void ListRpcRequest::InitAsDefaultInstance() {
}

ListRpcRequest::ListRpcRequest(const ListRpcRequest& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protorpc.ListRpcRequest)
}

void ListRpcRequest::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  service_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  list_method_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ListRpcRequest::~ListRpcRequest() {
  // @@protoc_insertion_point(destructor:protorpc.ListRpcRequest)
  SharedDtor();
}

void ListRpcRequest::SharedDtor() {
  service_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void ListRpcRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ListRpcRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ListRpcRequest_descriptor_;
}

const ListRpcRequest& ListRpcRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcservice_2eproto();
  return *default_instance_;
}

ListRpcRequest* ListRpcRequest::default_instance_ = NULL;

ListRpcRequest* ListRpcRequest::New(::google::protobuf::Arena* arena) const {
  ListRpcRequest* n = new ListRpcRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ListRpcRequest::Clear() {
  if (_has_bits_[0 / 32] & 3u) {
    if (has_service_name()) {
      service_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    list_method_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ListRpcRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protorpc.ListRpcRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string service_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_service_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->service_name().data(), this->service_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "protorpc.ListRpcRequest.service_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_list_method;
        break;
      }

      // optional bool list_method = 2;
      case 2: {
        if (tag == 16) {
         parse_list_method:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &list_method_)));
          set_has_list_method();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protorpc.ListRpcRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protorpc.ListRpcRequest)
  return false;
#undef DO_
}

void ListRpcRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protorpc.ListRpcRequest)
  // optional string service_name = 1;
  if (has_service_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->service_name().data(), this->service_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.ListRpcRequest.service_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->service_name(), output);
  }

  // optional bool list_method = 2;
  if (has_list_method()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->list_method(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:protorpc.ListRpcRequest)
}

::google::protobuf::uint8* ListRpcRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protorpc.ListRpcRequest)
  // optional string service_name = 1;
  if (has_service_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->service_name().data(), this->service_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.ListRpcRequest.service_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->service_name(), target);
  }

  // optional bool list_method = 2;
  if (has_list_method()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->list_method(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protorpc.ListRpcRequest)
  return target;
}

int ListRpcRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 3u) {
    // optional string service_name = 1;
    if (has_service_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->service_name());
    }

    // optional bool list_method = 2;
    if (has_list_method()) {
      total_size += 1 + 1;
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ListRpcRequest::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ListRpcRequest* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ListRpcRequest>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ListRpcRequest::MergeFrom(const ListRpcRequest& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_service_name()) {
      set_has_service_name();
      service_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.service_name_);
    }
    if (from.has_list_method()) {
      set_list_method(from.list_method());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void ListRpcRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListRpcRequest::CopyFrom(const ListRpcRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListRpcRequest::IsInitialized() const {

  return true;
}

void ListRpcRequest::Swap(ListRpcRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ListRpcRequest::InternalSwap(ListRpcRequest* other) {
  service_name_.Swap(&other->service_name_);
  std::swap(list_method_, other->list_method_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ListRpcRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ListRpcRequest_descriptor_;
  metadata.reflection = ListRpcRequest_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ListRpcRequest

// optional string service_name = 1;
bool ListRpcRequest::has_service_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ListRpcRequest::set_has_service_name() {
  _has_bits_[0] |= 0x00000001u;
}
void ListRpcRequest::clear_has_service_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void ListRpcRequest::clear_service_name() {
  service_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_service_name();
}
 const ::std::string& ListRpcRequest::service_name() const {
  // @@protoc_insertion_point(field_get:protorpc.ListRpcRequest.service_name)
  return service_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ListRpcRequest::set_service_name(const ::std::string& value) {
  set_has_service_name();
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protorpc.ListRpcRequest.service_name)
}
 void ListRpcRequest::set_service_name(const char* value) {
  set_has_service_name();
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protorpc.ListRpcRequest.service_name)
}
 void ListRpcRequest::set_service_name(const char* value, size_t size) {
  set_has_service_name();
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protorpc.ListRpcRequest.service_name)
}
 ::std::string* ListRpcRequest::mutable_service_name() {
  set_has_service_name();
  // @@protoc_insertion_point(field_mutable:protorpc.ListRpcRequest.service_name)
  return service_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ListRpcRequest::release_service_name() {
  clear_has_service_name();
  return service_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ListRpcRequest::set_allocated_service_name(::std::string* service_name) {
  if (service_name != NULL) {
    set_has_service_name();
  } else {
    clear_has_service_name();
  }
  service_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), service_name);
  // @@protoc_insertion_point(field_set_allocated:protorpc.ListRpcRequest.service_name)
}

// optional bool list_method = 2;
bool ListRpcRequest::has_list_method() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ListRpcRequest::set_has_list_method() {
  _has_bits_[0] |= 0x00000002u;
}
void ListRpcRequest::clear_has_list_method() {
  _has_bits_[0] &= ~0x00000002u;
}
void ListRpcRequest::clear_list_method() {
  list_method_ = false;
  clear_has_list_method();
}
 bool ListRpcRequest::list_method() const {
  // @@protoc_insertion_point(field_get:protorpc.ListRpcRequest.list_method)
  return list_method_;
}
 void ListRpcRequest::set_list_method(bool value) {
  set_has_list_method();
  list_method_ = value;
  // @@protoc_insertion_point(field_set:protorpc.ListRpcRequest.list_method)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int ListRpcResponse::kErrorFieldNumber;
const int ListRpcResponse::kServiceNameFieldNumber;
const int ListRpcResponse::kMethodNameFieldNumber;
#endif  // !_MSC_VER

ListRpcResponse::ListRpcResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protorpc.ListRpcResponse)
}

void ListRpcResponse::InitAsDefaultInstance() {
}

ListRpcResponse::ListRpcResponse(const ListRpcResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protorpc.ListRpcResponse)
}

void ListRpcResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  error_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ListRpcResponse::~ListRpcResponse() {
  // @@protoc_insertion_point(destructor:protorpc.ListRpcResponse)
  SharedDtor();
}

void ListRpcResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ListRpcResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ListRpcResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ListRpcResponse_descriptor_;
}

const ListRpcResponse& ListRpcResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcservice_2eproto();
  return *default_instance_;
}

ListRpcResponse* ListRpcResponse::default_instance_ = NULL;

ListRpcResponse* ListRpcResponse::New(::google::protobuf::Arena* arena) const {
  ListRpcResponse* n = new ListRpcResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ListRpcResponse::Clear() {
  error_ = 0;
  service_name_.Clear();
  method_name_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ListRpcResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protorpc.ListRpcResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .protorpc.ErrorCode error = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::protorpc::ErrorCode_IsValid(value)) {
            set_error(static_cast< ::protorpc::ErrorCode >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_service_name;
        break;
      }

      // repeated string service_name = 2;
      case 2: {
        if (tag == 18) {
         parse_service_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_service_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->service_name(this->service_name_size() - 1).data(),
            this->service_name(this->service_name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "protorpc.ListRpcResponse.service_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_service_name;
        if (input->ExpectTag(26)) goto parse_method_name;
        break;
      }

      // repeated string method_name = 3;
      case 3: {
        if (tag == 26) {
         parse_method_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_method_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->method_name(this->method_name_size() - 1).data(),
            this->method_name(this->method_name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "protorpc.ListRpcResponse.method_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_method_name;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protorpc.ListRpcResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protorpc.ListRpcResponse)
  return false;
#undef DO_
}

void ListRpcResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protorpc.ListRpcResponse)
  // required .protorpc.ErrorCode error = 1;
  if (has_error()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->error(), output);
  }

  // repeated string service_name = 2;
  for (int i = 0; i < this->service_name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->service_name(i).data(), this->service_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.ListRpcResponse.service_name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->service_name(i), output);
  }

  // repeated string method_name = 3;
  for (int i = 0; i < this->method_name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->method_name(i).data(), this->method_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.ListRpcResponse.method_name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->method_name(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:protorpc.ListRpcResponse)
}

::google::protobuf::uint8* ListRpcResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protorpc.ListRpcResponse)
  // required .protorpc.ErrorCode error = 1;
  if (has_error()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->error(), target);
  }

  // repeated string service_name = 2;
  for (int i = 0; i < this->service_name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->service_name(i).data(), this->service_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.ListRpcResponse.service_name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->service_name(i), target);
  }

  // repeated string method_name = 3;
  for (int i = 0; i < this->method_name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->method_name(i).data(), this->method_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.ListRpcResponse.method_name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->method_name(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protorpc.ListRpcResponse)
  return target;
}

int ListRpcResponse::ByteSize() const {
  int total_size = 0;

  // required .protorpc.ErrorCode error = 1;
  if (has_error()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->error());
  }
  // repeated string service_name = 2;
  total_size += 1 * this->service_name_size();
  for (int i = 0; i < this->service_name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->service_name(i));
  }

  // repeated string method_name = 3;
  total_size += 1 * this->method_name_size();
  for (int i = 0; i < this->method_name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->method_name(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ListRpcResponse::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ListRpcResponse* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ListRpcResponse>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ListRpcResponse::MergeFrom(const ListRpcResponse& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  service_name_.MergeFrom(from.service_name_);
  method_name_.MergeFrom(from.method_name_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_error()) {
      set_error(from.error());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void ListRpcResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListRpcResponse::CopyFrom(const ListRpcResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListRpcResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ListRpcResponse::Swap(ListRpcResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ListRpcResponse::InternalSwap(ListRpcResponse* other) {
  std::swap(error_, other->error_);
  service_name_.UnsafeArenaSwap(&other->service_name_);
  method_name_.UnsafeArenaSwap(&other->method_name_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ListRpcResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ListRpcResponse_descriptor_;
  metadata.reflection = ListRpcResponse_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ListRpcResponse

// required .protorpc.ErrorCode error = 1;
bool ListRpcResponse::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ListRpcResponse::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
void ListRpcResponse::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
void ListRpcResponse::clear_error() {
  error_ = 0;
  clear_has_error();
}
 ::protorpc::ErrorCode ListRpcResponse::error() const {
  // @@protoc_insertion_point(field_get:protorpc.ListRpcResponse.error)
  return static_cast< ::protorpc::ErrorCode >(error_);
}
 void ListRpcResponse::set_error(::protorpc::ErrorCode value) {
  assert(::protorpc::ErrorCode_IsValid(value));
  set_has_error();
  error_ = value;
  // @@protoc_insertion_point(field_set:protorpc.ListRpcResponse.error)
}

// repeated string service_name = 2;
int ListRpcResponse::service_name_size() const {
  return service_name_.size();
}
void ListRpcResponse::clear_service_name() {
  service_name_.Clear();
}
 const ::std::string& ListRpcResponse::service_name(int index) const {
  // @@protoc_insertion_point(field_get:protorpc.ListRpcResponse.service_name)
  return service_name_.Get(index);
}
 ::std::string* ListRpcResponse::mutable_service_name(int index) {
  // @@protoc_insertion_point(field_mutable:protorpc.ListRpcResponse.service_name)
  return service_name_.Mutable(index);
}
 void ListRpcResponse::set_service_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:protorpc.ListRpcResponse.service_name)
  service_name_.Mutable(index)->assign(value);
}
 void ListRpcResponse::set_service_name(int index, const char* value) {
  service_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:protorpc.ListRpcResponse.service_name)
}
 void ListRpcResponse::set_service_name(int index, const char* value, size_t size) {
  service_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protorpc.ListRpcResponse.service_name)
}
 ::std::string* ListRpcResponse::add_service_name() {
  return service_name_.Add();
}
 void ListRpcResponse::add_service_name(const ::std::string& value) {
  service_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:protorpc.ListRpcResponse.service_name)
}
 void ListRpcResponse::add_service_name(const char* value) {
  service_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:protorpc.ListRpcResponse.service_name)
}
 void ListRpcResponse::add_service_name(const char* value, size_t size) {
  service_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:protorpc.ListRpcResponse.service_name)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
ListRpcResponse::service_name() const {
  // @@protoc_insertion_point(field_list:protorpc.ListRpcResponse.service_name)
  return service_name_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
ListRpcResponse::mutable_service_name() {
  // @@protoc_insertion_point(field_mutable_list:protorpc.ListRpcResponse.service_name)
  return &service_name_;
}

// repeated string method_name = 3;
int ListRpcResponse::method_name_size() const {
  return method_name_.size();
}
void ListRpcResponse::clear_method_name() {
  method_name_.Clear();
}
 const ::std::string& ListRpcResponse::method_name(int index) const {
  // @@protoc_insertion_point(field_get:protorpc.ListRpcResponse.method_name)
  return method_name_.Get(index);
}
 ::std::string* ListRpcResponse::mutable_method_name(int index) {
  // @@protoc_insertion_point(field_mutable:protorpc.ListRpcResponse.method_name)
  return method_name_.Mutable(index);
}
 void ListRpcResponse::set_method_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:protorpc.ListRpcResponse.method_name)
  method_name_.Mutable(index)->assign(value);
}
 void ListRpcResponse::set_method_name(int index, const char* value) {
  method_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:protorpc.ListRpcResponse.method_name)
}
 void ListRpcResponse::set_method_name(int index, const char* value, size_t size) {
  method_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protorpc.ListRpcResponse.method_name)
}
 ::std::string* ListRpcResponse::add_method_name() {
  return method_name_.Add();
}
 void ListRpcResponse::add_method_name(const ::std::string& value) {
  method_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:protorpc.ListRpcResponse.method_name)
}
 void ListRpcResponse::add_method_name(const char* value) {
  method_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:protorpc.ListRpcResponse.method_name)
}
 void ListRpcResponse::add_method_name(const char* value, size_t size) {
  method_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:protorpc.ListRpcResponse.method_name)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
ListRpcResponse::method_name() const {
  // @@protoc_insertion_point(field_list:protorpc.ListRpcResponse.method_name)
  return method_name_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
ListRpcResponse::mutable_method_name() {
  // @@protoc_insertion_point(field_mutable_list:protorpc.ListRpcResponse.method_name)
  return &method_name_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int GetServiceRequest::kServiceNameFieldNumber;
#endif  // !_MSC_VER

GetServiceRequest::GetServiceRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protorpc.GetServiceRequest)
}

void GetServiceRequest::InitAsDefaultInstance() {
}

GetServiceRequest::GetServiceRequest(const GetServiceRequest& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protorpc.GetServiceRequest)
}

void GetServiceRequest::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  service_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GetServiceRequest::~GetServiceRequest() {
  // @@protoc_insertion_point(destructor:protorpc.GetServiceRequest)
  SharedDtor();
}

void GetServiceRequest::SharedDtor() {
  service_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void GetServiceRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetServiceRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetServiceRequest_descriptor_;
}

const GetServiceRequest& GetServiceRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcservice_2eproto();
  return *default_instance_;
}

GetServiceRequest* GetServiceRequest::default_instance_ = NULL;

GetServiceRequest* GetServiceRequest::New(::google::protobuf::Arena* arena) const {
  GetServiceRequest* n = new GetServiceRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetServiceRequest::Clear() {
  if (has_service_name()) {
    service_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool GetServiceRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protorpc.GetServiceRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string service_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_service_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->service_name().data(), this->service_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "protorpc.GetServiceRequest.service_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protorpc.GetServiceRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protorpc.GetServiceRequest)
  return false;
#undef DO_
}

void GetServiceRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protorpc.GetServiceRequest)
  // required string service_name = 1;
  if (has_service_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->service_name().data(), this->service_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.GetServiceRequest.service_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->service_name(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:protorpc.GetServiceRequest)
}

::google::protobuf::uint8* GetServiceRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protorpc.GetServiceRequest)
  // required string service_name = 1;
  if (has_service_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->service_name().data(), this->service_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.GetServiceRequest.service_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->service_name(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protorpc.GetServiceRequest)
  return target;
}

int GetServiceRequest::ByteSize() const {
  int total_size = 0;

  // required string service_name = 1;
  if (has_service_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->service_name());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetServiceRequest::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const GetServiceRequest* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const GetServiceRequest>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GetServiceRequest::MergeFrom(const GetServiceRequest& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_service_name()) {
      set_has_service_name();
      service_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.service_name_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void GetServiceRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetServiceRequest::CopyFrom(const GetServiceRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetServiceRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void GetServiceRequest::Swap(GetServiceRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetServiceRequest::InternalSwap(GetServiceRequest* other) {
  service_name_.Swap(&other->service_name_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetServiceRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetServiceRequest_descriptor_;
  metadata.reflection = GetServiceRequest_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetServiceRequest

// required string service_name = 1;
bool GetServiceRequest::has_service_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void GetServiceRequest::set_has_service_name() {
  _has_bits_[0] |= 0x00000001u;
}
void GetServiceRequest::clear_has_service_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void GetServiceRequest::clear_service_name() {
  service_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_service_name();
}
 const ::std::string& GetServiceRequest::service_name() const {
  // @@protoc_insertion_point(field_get:protorpc.GetServiceRequest.service_name)
  return service_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetServiceRequest::set_service_name(const ::std::string& value) {
  set_has_service_name();
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protorpc.GetServiceRequest.service_name)
}
 void GetServiceRequest::set_service_name(const char* value) {
  set_has_service_name();
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protorpc.GetServiceRequest.service_name)
}
 void GetServiceRequest::set_service_name(const char* value, size_t size) {
  set_has_service_name();
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protorpc.GetServiceRequest.service_name)
}
 ::std::string* GetServiceRequest::mutable_service_name() {
  set_has_service_name();
  // @@protoc_insertion_point(field_mutable:protorpc.GetServiceRequest.service_name)
  return service_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GetServiceRequest::release_service_name() {
  clear_has_service_name();
  return service_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetServiceRequest::set_allocated_service_name(::std::string* service_name) {
  if (service_name != NULL) {
    set_has_service_name();
  } else {
    clear_has_service_name();
  }
  service_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), service_name);
  // @@protoc_insertion_point(field_set_allocated:protorpc.GetServiceRequest.service_name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int GetServiceResponse::kErrorFieldNumber;
const int GetServiceResponse::kProtoFileFieldNumber;
const int GetServiceResponse::kProtoFileNameFieldNumber;
#endif  // !_MSC_VER

GetServiceResponse::GetServiceResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protorpc.GetServiceResponse)
}

void GetServiceResponse::InitAsDefaultInstance() {
}

GetServiceResponse::GetServiceResponse(const GetServiceResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protorpc.GetServiceResponse)
}

void GetServiceResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  error_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GetServiceResponse::~GetServiceResponse() {
  // @@protoc_insertion_point(destructor:protorpc.GetServiceResponse)
  SharedDtor();
}

void GetServiceResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GetServiceResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetServiceResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetServiceResponse_descriptor_;
}

const GetServiceResponse& GetServiceResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcservice_2eproto();
  return *default_instance_;
}

GetServiceResponse* GetServiceResponse::default_instance_ = NULL;

GetServiceResponse* GetServiceResponse::New(::google::protobuf::Arena* arena) const {
  GetServiceResponse* n = new GetServiceResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetServiceResponse::Clear() {
  error_ = 0;
  proto_file_.Clear();
  proto_file_name_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool GetServiceResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protorpc.GetServiceResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .protorpc.ErrorCode error = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::protorpc::ErrorCode_IsValid(value)) {
            set_error(static_cast< ::protorpc::ErrorCode >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_proto_file;
        break;
      }

      // repeated string proto_file = 2;
      case 2: {
        if (tag == 18) {
         parse_proto_file:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_proto_file()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->proto_file(this->proto_file_size() - 1).data(),
            this->proto_file(this->proto_file_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "protorpc.GetServiceResponse.proto_file");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_proto_file;
        if (input->ExpectTag(26)) goto parse_proto_file_name;
        break;
      }

      // repeated string proto_file_name = 3;
      case 3: {
        if (tag == 26) {
         parse_proto_file_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_proto_file_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->proto_file_name(this->proto_file_name_size() - 1).data(),
            this->proto_file_name(this->proto_file_name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "protorpc.GetServiceResponse.proto_file_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_proto_file_name;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protorpc.GetServiceResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protorpc.GetServiceResponse)
  return false;
#undef DO_
}

void GetServiceResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protorpc.GetServiceResponse)
  // required .protorpc.ErrorCode error = 1;
  if (has_error()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->error(), output);
  }

  // repeated string proto_file = 2;
  for (int i = 0; i < this->proto_file_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->proto_file(i).data(), this->proto_file(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.GetServiceResponse.proto_file");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->proto_file(i), output);
  }

  // repeated string proto_file_name = 3;
  for (int i = 0; i < this->proto_file_name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->proto_file_name(i).data(), this->proto_file_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.GetServiceResponse.proto_file_name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->proto_file_name(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:protorpc.GetServiceResponse)
}

::google::protobuf::uint8* GetServiceResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protorpc.GetServiceResponse)
  // required .protorpc.ErrorCode error = 1;
  if (has_error()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->error(), target);
  }

  // repeated string proto_file = 2;
  for (int i = 0; i < this->proto_file_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->proto_file(i).data(), this->proto_file(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.GetServiceResponse.proto_file");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->proto_file(i), target);
  }

  // repeated string proto_file_name = 3;
  for (int i = 0; i < this->proto_file_name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->proto_file_name(i).data(), this->proto_file_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protorpc.GetServiceResponse.proto_file_name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->proto_file_name(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protorpc.GetServiceResponse)
  return target;
}

int GetServiceResponse::ByteSize() const {
  int total_size = 0;

  // required .protorpc.ErrorCode error = 1;
  if (has_error()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->error());
  }
  // repeated string proto_file = 2;
  total_size += 1 * this->proto_file_size();
  for (int i = 0; i < this->proto_file_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->proto_file(i));
  }

  // repeated string proto_file_name = 3;
  total_size += 1 * this->proto_file_name_size();
  for (int i = 0; i < this->proto_file_name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->proto_file_name(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetServiceResponse::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const GetServiceResponse* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const GetServiceResponse>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GetServiceResponse::MergeFrom(const GetServiceResponse& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  proto_file_.MergeFrom(from.proto_file_);
  proto_file_name_.MergeFrom(from.proto_file_name_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_error()) {
      set_error(from.error());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void GetServiceResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetServiceResponse::CopyFrom(const GetServiceResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetServiceResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void GetServiceResponse::Swap(GetServiceResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetServiceResponse::InternalSwap(GetServiceResponse* other) {
  std::swap(error_, other->error_);
  proto_file_.UnsafeArenaSwap(&other->proto_file_);
  proto_file_name_.UnsafeArenaSwap(&other->proto_file_name_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetServiceResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetServiceResponse_descriptor_;
  metadata.reflection = GetServiceResponse_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetServiceResponse

// required .protorpc.ErrorCode error = 1;
bool GetServiceResponse::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void GetServiceResponse::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
void GetServiceResponse::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
void GetServiceResponse::clear_error() {
  error_ = 0;
  clear_has_error();
}
 ::protorpc::ErrorCode GetServiceResponse::error() const {
  // @@protoc_insertion_point(field_get:protorpc.GetServiceResponse.error)
  return static_cast< ::protorpc::ErrorCode >(error_);
}
 void GetServiceResponse::set_error(::protorpc::ErrorCode value) {
  assert(::protorpc::ErrorCode_IsValid(value));
  set_has_error();
  error_ = value;
  // @@protoc_insertion_point(field_set:protorpc.GetServiceResponse.error)
}

// repeated string proto_file = 2;
int GetServiceResponse::proto_file_size() const {
  return proto_file_.size();
}
void GetServiceResponse::clear_proto_file() {
  proto_file_.Clear();
}
 const ::std::string& GetServiceResponse::proto_file(int index) const {
  // @@protoc_insertion_point(field_get:protorpc.GetServiceResponse.proto_file)
  return proto_file_.Get(index);
}
 ::std::string* GetServiceResponse::mutable_proto_file(int index) {
  // @@protoc_insertion_point(field_mutable:protorpc.GetServiceResponse.proto_file)
  return proto_file_.Mutable(index);
}
 void GetServiceResponse::set_proto_file(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:protorpc.GetServiceResponse.proto_file)
  proto_file_.Mutable(index)->assign(value);
}
 void GetServiceResponse::set_proto_file(int index, const char* value) {
  proto_file_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:protorpc.GetServiceResponse.proto_file)
}
 void GetServiceResponse::set_proto_file(int index, const char* value, size_t size) {
  proto_file_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protorpc.GetServiceResponse.proto_file)
}
 ::std::string* GetServiceResponse::add_proto_file() {
  return proto_file_.Add();
}
 void GetServiceResponse::add_proto_file(const ::std::string& value) {
  proto_file_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:protorpc.GetServiceResponse.proto_file)
}
 void GetServiceResponse::add_proto_file(const char* value) {
  proto_file_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:protorpc.GetServiceResponse.proto_file)
}
 void GetServiceResponse::add_proto_file(const char* value, size_t size) {
  proto_file_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:protorpc.GetServiceResponse.proto_file)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
GetServiceResponse::proto_file() const {
  // @@protoc_insertion_point(field_list:protorpc.GetServiceResponse.proto_file)
  return proto_file_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
GetServiceResponse::mutable_proto_file() {
  // @@protoc_insertion_point(field_mutable_list:protorpc.GetServiceResponse.proto_file)
  return &proto_file_;
}

// repeated string proto_file_name = 3;
int GetServiceResponse::proto_file_name_size() const {
  return proto_file_name_.size();
}
void GetServiceResponse::clear_proto_file_name() {
  proto_file_name_.Clear();
}
 const ::std::string& GetServiceResponse::proto_file_name(int index) const {
  // @@protoc_insertion_point(field_get:protorpc.GetServiceResponse.proto_file_name)
  return proto_file_name_.Get(index);
}
 ::std::string* GetServiceResponse::mutable_proto_file_name(int index) {
  // @@protoc_insertion_point(field_mutable:protorpc.GetServiceResponse.proto_file_name)
  return proto_file_name_.Mutable(index);
}
 void GetServiceResponse::set_proto_file_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:protorpc.GetServiceResponse.proto_file_name)
  proto_file_name_.Mutable(index)->assign(value);
}
 void GetServiceResponse::set_proto_file_name(int index, const char* value) {
  proto_file_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:protorpc.GetServiceResponse.proto_file_name)
}
 void GetServiceResponse::set_proto_file_name(int index, const char* value, size_t size) {
  proto_file_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protorpc.GetServiceResponse.proto_file_name)
}
 ::std::string* GetServiceResponse::add_proto_file_name() {
  return proto_file_name_.Add();
}
 void GetServiceResponse::add_proto_file_name(const ::std::string& value) {
  proto_file_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:protorpc.GetServiceResponse.proto_file_name)
}
 void GetServiceResponse::add_proto_file_name(const char* value) {
  proto_file_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:protorpc.GetServiceResponse.proto_file_name)
}
 void GetServiceResponse::add_proto_file_name(const char* value, size_t size) {
  proto_file_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:protorpc.GetServiceResponse.proto_file_name)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
GetServiceResponse::proto_file_name() const {
  // @@protoc_insertion_point(field_list:protorpc.GetServiceResponse.proto_file_name)
  return proto_file_name_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
GetServiceResponse::mutable_proto_file_name() {
  // @@protoc_insertion_point(field_mutable_list:protorpc.GetServiceResponse.proto_file_name)
  return &proto_file_name_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

RpcService::~RpcService() {}

const ::google::protobuf::ServiceDescriptor* RpcService::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RpcService_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* RpcService::GetDescriptor() {
  protobuf_AssignDescriptorsOnce();
  return RpcService_descriptor_;
}

void RpcService::listRpc(::google::protobuf::RpcController* controller,
                         const ::protorpc::ListRpcRequest*,
                         ::protorpc::ListRpcResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method listRpc() not implemented.");
  done->Run();
}

void RpcService::getService(::google::protobuf::RpcController* controller,
                         const ::protorpc::GetServiceRequest*,
                         ::protorpc::GetServiceResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method getService() not implemented.");
  done->Run();
}

void RpcService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), RpcService_descriptor_);
  switch(method->index()) {
    case 0:
      listRpc(controller,
             ::google::protobuf::down_cast<const ::protorpc::ListRpcRequest*>(request),
             ::google::protobuf::down_cast< ::protorpc::ListRpcResponse*>(response),
             done);
      break;
    case 1:
      getService(controller,
             ::google::protobuf::down_cast<const ::protorpc::GetServiceRequest*>(request),
             ::google::protobuf::down_cast< ::protorpc::GetServiceResponse*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& RpcService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::protorpc::ListRpcRequest::default_instance();
    case 1:
      return ::protorpc::GetServiceRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *static_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& RpcService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::protorpc::ListRpcResponse::default_instance();
    case 1:
      return ::protorpc::GetServiceResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *static_cast< ::google::protobuf::Message*>(NULL);
  }
}

RpcService_Stub::RpcService_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
RpcService_Stub::RpcService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
RpcService_Stub::~RpcService_Stub() {
  if (owns_channel_) delete channel_;
}

void RpcService_Stub::listRpc(::google::protobuf::RpcController* controller,
                              const ::protorpc::ListRpcRequest* request,
                              ::protorpc::ListRpcResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void RpcService_Stub::getService(::google::protobuf::RpcController* controller,
                              const ::protorpc::GetServiceRequest* request,
                              ::protorpc::GetServiceResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace protorpc

// @@protoc_insertion_point(global_scope)
